### ISSUE TITLE
Submitting gists that fail to compile

### ISSUE THREAD

**Issue by thedejifab** [divyanshub024/awesome-dart-pad#15]
@divyanshub024 I made a DartPad sample that basically shows pagination in action when fetching data over a network request to help newcomers due to the fact that I had problems with pagination without the use of third-party plugins earlier on.

Sadly, my example necessarily relies on the HTTP package and DartPad doesn't support importing external packages yet, hence, causing my code to fail to compile on DartPad. 

Can I make a pull request for such snippet here?

**Comment by NoobSolver** [comment]
@thedejifab I think you can make pr for that..

**Comment by divyanshub024** [comment]
Hey @thedejifab!! I don't think so that it's a great idea to show pagination on DartPad (due to the reasons you mentioned). 
If you want to help the newcomers with pagination it's better to write a blog about it.

**Comment by divyanshub024** [comment]
Another way for it could be by using the dummy data instead of fetching it from the network. This way you won't need the HTTP package and can create a DartPad sample.
