### ISSUE TITLE
Adding a gist to awesome-dart-pad

### ISSUE THREAD

**Issue by jayanthjj** [divyanshub024/awesome-dart-pad#3]
I would like to merge my gist https://gist.github.com/53fe98f3984e8b70dcfd0c784653e5fb.git should I do a PR or an issue is enough?
Link to the project https://github.com/jayanthj737/Flutter-Portfolio-App

**Comment by divyanshub024** [comment]
@jayanthj737 Please create a PR.

**Comment by divyanshub024** [comment]
@jayanthj737 Closing this issue, Let me know if you need any help.
