### ISSUE TITLE
Flutter Sample Slivers

### ISSUE THREAD

**Issue by GAyan17** [divyanshub024/awesome-dart-pad#8]
I want to add my sample Flutter app, DartPad Link: https://dartpad.dev/69a37eff10830b8efdce7dc374f923db.

But I'm not able to create a PR. Could you help me out? @divyanshub024

**Comment by divyanshub024** [comment]
@GAyan17 You need to fork the repo and then create a PR.

**Comment by GAyan17** [comment]
Okay, I'll try again after forking it. Thanks.

**Comment by GAyan17** [comment]
Do I have to first change in the readme?

**Comment by divyanshub024** [comment]
Yes.

**Comment by GAyan17** [comment]
@divyanshub024  I'm trying to do a PR but it always giving me an error 403, permission denied.
What's that about?

**Comment by divyanshub024** [comment]
@GAyan17 check this [blog](https://codeburst.io/a-step-by-step-guide-to-making-your-first-github-contribution-5302260a2940) to learn how to contribute.

**Comment by GAyan17** [comment]
@divyanshub024  Thanks for the help.
